export default [
  { label: "Abductors", value: "Abductors" },
  { label: "Abs", value: "Abs" },
  { label: "Adductors", value: "Adductors" },
  { label: "Biceps", value: "Biceps" },
  { label: "Calves", value: "Calves" },
  { label: "Chest", value: "Chest" },
  { label: "Forearms", value: "Forearms" },
  { label: "Glutes", value: "Glutes" },
  { label: "Hamstrings", value: "Hamstrings" },
  { label: "Lats", value: "Lats" },
  { label: "Lower Back", value: "Lower Back" },
  { label: "Middle Back", value: "Middle Back" },
  { label: "Neck", value: "Neck" },
  { label: "Quads", value: "Quads" },
  { label: "Shoulders", value: "Shoulders" },
  { label: "Traps", value: "Traps" },
  { label: "Triceps", value: "Triceps" },
  { label: "Upper Back", value: "Upper Back" },
];
